spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MYSQL #in memory db
    username: admin
    password: admin
    validationQuery: SELECT 1
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

loadBalancer:
#  mode: roundRobin
#  mode: leastConnection
#  Stickyness: true
